version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "1313:80"
    depends_on:
      - mysql

  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "127.0.0.1:1314:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

